export const tag = {
  'area': [
    { 'id': -100, 'name': '全部' },
    { 'id': 200, 'name': '内地' },
    { 'id': 2, 'name': '港台' },
    { 'id': 5, 'name': '欧美' },
    { 'id': 4, 'name': '日本' },
    { 'id': 3, 'name': '韩国' },
    { 'id': 6, 'name': '其他' }
  ],
  'genre': [
    { 'id': -100, 'name': '全部' },
    { 'id': 1, 'name': '流行' },
    { 'id': 6, 'name': '嘻哈' },
    { 'id': 2, 'name': '摇滚' },
    { 'id': 4, 'name': '电子' },
    { 'id': 3, 'name': '民谣' },
    { 'id': 8, 'name': 'R&B' },
    { 'id': 10, 'name': '民歌' },
    { 'id': 9, 'name': '轻音乐' },
    { 'id': 5, 'name': '爵士' },
    { 'id': 14, 'name': '古典' },
    { 'id': 25, 'name': '乡村' },
    { 'id': 20, 'name': '蓝调' }
  ],
  'index': [
    { 'id': -100, 'name': '热门' },
    { 'id': 1, 'name': 'A' },
    { 'id': 2, 'name': 'B' },
    { 'id': 3, 'name': 'C' },
    { 'id': 4, 'name': 'D' },
    { 'id': 5, 'name': 'E' },
    { 'id': 6, 'name': 'F' },
    { 'id': 7, 'name': 'G' },
    { 'id': 8, 'name': 'H' },
    { 'id': 9, 'name': 'I' },
    { 'id': 10, 'name': 'J' },
    { 'id': 11, 'name': 'K' },
    { 'id': 12, 'name': 'L' },
    { 'id': 13, 'name': 'M' },
    { 'id': 14, 'name': 'N' },
    { 'id': 15, 'name': 'O' },
    { 'id': 16, 'name': 'P' },
    { 'id': 17, 'name': 'Q' },
    { 'id': 18, 'name': 'R' },
    { 'id': 19, 'name': 'S' },
    { 'id': 20, 'name': 'T' },
    { 'id': 21, 'name': 'U' },
    { 'id': 22, 'name': 'V' },
    { 'id': 23, 'name': 'W' },
    { 'id': 24, 'name': 'X' },
    { 'id': 25, 'name': 'Y' },
    { 'id': 26, 'name': 'Z' },
    { 'id': 27, 'name': '#' }
  ],
  'sex': [
    { 'id': -100, 'name': '全部' },
    { 'id': 0, 'name': '男' },
    { 'id': 1, 'name': '女' },
    { 'id': 2, 'name': '组合' }
  ]
}
export let singertypeList = {
  '全部': 'all_all',
  '华语男': 'cn_man',
  '华语女': 'cn_woman',
  '华语组合': 'cn_team',
  '韩国男': 'k_man',
  '韩国女': 'k_woman',
  '韩国组合': 'k_team',
  '日本男': 'j_man',
  '日本女': 'j_woman',
  '日本组合': 'j_team',
  '欧美男': 'eu_man',
  '欧美女': 'eu_woman',
  '欧美组合': 'eu_team',
  '乐团': 'c_orchestra',
  '演奏家': 'c_performer',
  '作曲家': 'c_composer',
  '指挥家': 'c_cantor',
  '其他': 'other_other'
}

export let singerNameList = {
  '热门': 'all',
  'A': 'A',
  'B': 'B',
  'C': 'C',
  'D': 'D',
  'E': 'E',
  'F': 'F',
  'G': 'G',
  'H': 'H',
  'I': 'I',
  'J': 'J',
  'K': 'K',
  'L': 'L',
  'M': 'M',
  'N': 'N',
  'O': 'O',
  'P': 'P',
  'Q': 'Q',
  'R': 'R',
  'S': 'S',
  'T': 'T',
  'U': 'U',
  'V': 'V',
  'W': 'W',
  'X': 'X',
  'Y': 'Y',
  'Z': 'Z'
}
