export const COUNTRYLIST = {
  '全部': 'all_all',
  '华语男': 'cn_man',
  '华语女': 'cn_woman',
  '华语组合': 'cn_team',
  '韩国男': 'k_man',
  '韩国女': 'k_woman',
  '韩国组合': 'k_team',
  '日本男': 'j_man',
  '日本女': 'j_woman',
  '日本组合': 'j_team',
  '欧美男': 'eu_man',
  '欧美女': 'eu_woman',
  '欧美组合': 'eu_team',
  '乐团': 'c_orchestra',
  '演奏家': 'c_performer',
  '作曲家': 'c_composer',
  '指挥家': 'c_cantor',
  '其他': 'other_other'
}

export const FIRSTNAMELIST = {
  '热门': 'all',
  'A': 'A',
  'B': 'B',
  'C': 'C',
  'D': 'D',
  'E': 'E',
  'F': 'F',
  'G': 'G',
  'H': 'H',
  'I': 'I',
  'J': 'J',
  'K': 'K',
  'L': 'L',
  'M': 'M',
  'N': 'N',
  'O': 'O',
  'P': 'P',
  'Q': 'Q',
  'R': 'R',
  'S': 'S',
  'T': 'T',
  'U': 'U',
  'V': 'V',
  'W': 'W',
  'X': 'X',
  'Y': 'Y',
  'Z': 'Z'
}
